Factory/Models/DesignTimeDbContextFactory.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Design;
using Microsoft.Extensions.Configuration;
using System.IO;

namespace Factory.Models
{
  public class FactoryContextFactory : IDesignTimeDbContextFactory<FactoryContext>
  {

    FactoryContext IDesignTimeDbContextFactory<FactoryContext>.CreateDbContext(string[] args)
    {
      IConfigurationRoot configuration = new ConfigurationBuilder()
          .SetBasePath(Directory.GetCurrentDirectory())
          .AddJsonFile("appsettings.json")
          .Build();

      var builder = new DbContextOptionsBuilder<FactoryContext>();
      var connectionString = configuration.GetConnectionString("DefaultConnection");

      builder.UseMySql(connectionString);

      return new FactoryContext(builder.Options);
    }
  }
}

Factory/Models/Engineer.cs
using System;
using System.Collections.Generic;

namespace Factory.Models
{
  public class Engineer
  {
    public Engineer()
    {
      this.Machines = new HashSet<EngineerMachine>();
    }
    public int EngineerId { get; set; }
    public string Name { get; set; }
    public string Availability { get; set; }
    public DateTime HireDate { get; set; }
    public int ExperienceLevel { get; set; }
    public ICollection<EngineerMachine> Machines { get; set; }
  }
}

Factory/Models/EngineerMachine.cs
namespace Factory.Models
{
  public class EngineerMachine
  {
    public int EngineerMachineId { get; set; }
    public int EngineerId { get; set; }
    public int MachineId { get; set; }
    public Engineer Engineer { get; set; }
    public Machine Machine { get; set; }
  }
}

Factory/Models/FactoryContext.cs
using Microsoft.EntityFrameworkCore;

namespace Factory.Models
{
  public class FactoryContext : DbContext
  {
    public virtual DbSet<Engineer> Engineers { get; set; }
    public DbSet<Machine> Machines { get; set; }
    public DbSet<EngineerMachine> EngineerMachine { get; set; }
    public FactoryContext(DbContextOptions options) : base(options) { }
  }
}

Factory/Models/Machine.cs
using System;
using System.Collections.Generic;

namespace Factory.Models
{
  public class Machine
  {
    public Machine()
    {
      this.Engineers = new HashSet<EngineerMachine>();
    }
    public int MachineId { get; set; }
    public string Model { get; set; }
    public string Manufacturer { get; set; }
    public int YearsInOperation { get; set; }
    public DateTime LastServiced { get; set; }
    public string MaintenanceInterval { get; set; }
    public ICollection<EngineerMachine> Engineers { get; set; }
  }
}

Factory/Controllers/EngineersController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using Factory.Models;
using System.Collections.Generic;
using System.Linq;

namespace Factory.Controllers
{
  public class EngineersController : Controller 
  {
    private readonly FactoryContext _db;
    public EngineersController(FactoryContext db)
    {
      _db = db;
    }
    public ActionResult Index()
    {
      return View(_db.Engineers.ToList());
    }
    public ActionResult Create()
    {
      return View();
    }
    [HttpPost]
    public ActionResult Create(Engineer engineer, int MachineId)
    {
      _db.Engineers.Add(engineer);
      _db.SaveChanges();
      return RedirectToAction("Index", "Home");
    }
    public ActionResult Details(int id)
    {
      var thisEngineer = _db.Engineers
        .Include(engineer => engineer.Machines)
        .ThenInclude(join => join.Machine)
        .FirstOrDefault(engineer => engineer.EngineerId == id);
        return View(thisEngineer);
    }
    public ActionResult Edit(int id)
    {
      var thisEngineer = _db.Engineers.FirstOrDefault(engineer => engineer.EngineerId == id);
      return View(thisEngineer);
    }

    [HttpPost]
    public ActionResult Edit(Engineer engineer, int MachineId)
    {
      _db.Entry(engineer).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index", "Home");
    }
    public ActionResult AddMachine(int id)
    {
      var thisEngineer= _db.Engineers.FirstOrDefault(engineer => engineer.EngineerId == id);
      ViewBag.MachineId = new SelectList(_db.Machines, "MachineId", "Model");
      return View(thisEngineer);
    }
    [HttpPost]
    public ActionResult AddMachine(Engineer engineer, int MachineId)
    {
      if (MachineId != 0)
      {
        _db.EngineerMachine.Add(new EngineerMachine() { MachineId = MachineId, EngineerId = engineer.EngineerId });
      }
      _db.SaveChanges();
      return RedirectToAction("Index", "Home");
    }
    public ActionResult Delete(int id)
    {
      var thisEngineer = _db.Engineers.FirstOrDefault(engineer => engineer.EngineerId == id);
      return View(thisEngineer);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisEngineer = _db.Engineers.FirstOrDefault(engineer => engineer.EngineerId == id);
      _db.Engineers.Remove(thisEngineer);
      _db.SaveChanges();
      return RedirectToAction("Index", "Home");
    }

    [HttpPost]
    public ActionResult DeleteMachine(int joinId)
    {
      var joinEntry = _db.EngineerMachine.FirstOrDefault(entry => entry.EngineerMachineId == joinId);
      _db.EngineerMachine.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index", "Home");
    }
  } 
}

Factory/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Factory.Models;
using System.Linq;

namespace Factory.Controllers
{
  public class HomeController : Controller
  {
    private readonly FactoryContext _db;
    public HomeController(FactoryContext db)
    {
      _db = db;
    }

    [HttpGet("/")]
    public ActionResult Index()
    {
      ViewBag.Engineers = _db.Engineers.ToList();
      ViewBag.Machines = _db.Machines.ToList();
      return View();
    }
  }
}

Factory/Controllers/MachinesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using Factory.Models;
using System.Collections.Generic;
using System.Linq;

namespace Factory.Controllers
{
  public class MachinesController : Controller 
  {
    private readonly FactoryContext _db;
    public MachinesController(FactoryContext db)
    {
      _db = db;
    }
    public ActionResult Index()
    {
      return View(_db.Machines.ToList());
    }
    public ActionResult Create()
    {
      return View();
    }
    [HttpPost]
    public ActionResult Create(Machine machine, int EngineerId)
    {
      _db.Machines.Add(machine);
      _db.SaveChanges();
      return RedirectToAction("Index", "Home");
    }
    public ActionResult Details(int id)
    {
      var thisMachine = _db.Machines
        .Include(machine => machine.Engineers)
        .ThenInclude(join => join.Engineer)
        .FirstOrDefault(machine => machine.MachineId == id);
        return View(thisMachine);
    }
    public ActionResult Edit(int id)
    {
      var thisMachine = _db.Machines.FirstOrDefault(machine => machine.MachineId == id);
      return View(thisMachine);
    }

    [HttpPost]
    public ActionResult Edit(Machine machine, int EngineerId)
    {
      _db.Entry(machine).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index", "Home");
    }
    public ActionResult AddEngineer(int id)
    {
      var thisMachine = _db.Machines.FirstOrDefault(machine => machine.MachineId == id);
      ViewBag.EngineerId = new SelectList(_db.Engineers, "EngineerId", "Name");
      return View(thisMachine);
    }
    [HttpPost]
    public ActionResult AddEngineer(Machine machine, int EngineerId)
    {
      if (EngineerId != 0)
      {
        _db.EngineerMachine.Add(new EngineerMachine() { EngineerId = EngineerId, MachineId = machine.MachineId });
      }
      _db.SaveChanges();
      return RedirectToAction("Index", "Home");
    }

    public ActionResult Delete(int id)
    {
      var thisMachine = _db.Machines.FirstOrDefault(machine => machine.MachineId == id);
      return View(thisMachine);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisMachine = _db.Machines.FirstOrDefault(machine => machine.MachineId == id);
      _db.Machines.Remove(thisMachine);
      _db.SaveChanges();
      return RedirectToAction("Index", "Home");
    }

    [HttpPost]
    public ActionResult DeleteEngineer(int joinId)
    {
      var joinEntry = _db.EngineerMachine.FirstOrDefault(entry => entry.EngineerMachineId == joinId);
      _db.EngineerMachine.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index", "Home");
    }
  }
}

Factory/Views/Engineers/AddMachine.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Engineer

<h2>Add Machine</h2>

<h4>Select a machine that @Html.DisplayFor(model => model.Name) is licensed to repair.</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.EngineerId)

  @Html.Label("Machine")
  @Html.DropDownList("MachineId")

  <input type="submit" class="btn btn-dark" value="Save" />
}

Factory/Views/Engineers/Create.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Engineer;

<h2>Add an Engineer</h2>

@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Name);
  @Html.TextBoxFor(model => model.Name, new { @class="form-control", required="required" });

  @Html.LabelFor(model => model.Availability);
  @Html.TextBoxFor(model => model.Availability, new { @class="form-control", required="required" });

  @Html.Label("Hire Date");
  @Html.TextBoxFor(model => model.HireDate, new { @type="date", @class="form-control", required="required" });

  @Html.Label("Experience Level");
  @Html.TextBoxFor(model => model.ExperienceLevel, new { @type="number", min="1", max="10", @class="form-control", required="required" });

  <input type="submit" class="btn btn-dark" value="Add Engineer" />
}

Factory/Views/Engineers/Delete.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Engineer

<h2>Delete Engineer: @Html.DisplayFor(model => model.Name)</h2>

<p>Are you sure you want to delete this engineer?</p>

@using (Html.BeginForm())
{
    <input type="submit" value="Delete" />
}

Factory/Views/Engineers/Details.cshtml
@{
  Layout ="_Layout";
}

@model Factory.Models.Engineer

<div class="details">
<h2>@Html.DisplayFor(model => model.Name)</h2>

<ul>
  <li>@Html.Label("Availability"): @Html.DisplayFor(model => model.Availability)</li>
  <li>@Html.Label("Hire Date"): @Html.DisplayFor(model => model.HireDate)</li>
  <li>@Html.Label("Experience Level"): @Html.DisplayFor(model => model.ExperienceLevel)</li>
  <li>@Html.Label("Licensed to work on"):
    <ul>
      @if (@Model.Machines.Count == 0)
      {
        <li>This engineer is not licensed to repair any machines.</li>
      }
      else
      {
        <ul>
          @foreach(var join in Model.Machines)
          {
            <li><h3>@Html.ActionLink($"{join.Machine.Model}", "Details", "Machines", new { id = join.Machine.MachineId })</h3></li>
            @using (Html.BeginForm("DeleteMachine", "Engineers"))
            {
              @Html.Hidden("joinId", @join.EngineerMachineId)
              <input type="submit" value="Delete"/>
            }
          }
        </ul>
      }
    </ul></li>
</ul>
</div>

<button class="btn btn-dark">@Html.ActionLink("Add a Machine", "AddMachine", new { id = Model.EngineerId })</button>
<button class="btn btn-dark">@Html.ActionLink("Edit Engineer", "Edit", new { id = @Model.EngineerId })</button>
<button class="btn btn-dark">@Html.ActionLink("Delete Engineer", "Delete", new { id = @Model.EngineerId })</button>

Factory/Views/Engineers/Edit.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Engineer

<h2>Edit: @Html.DisplayFor(model => model.Name)</h2>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.EngineerId)

    @Html.LabelFor(model => model.Name)
    @Html.TextBoxFor(model => model.Name,  new { @class="form-control", required="required" })

    @Html.LabelFor(model => model.Availability)
    @Html.TextBoxFor(model => model.Availability, new { @class="form-control", required="required" })

    @Html.Label("Hire Date");
    @Html.TextBoxFor(model => model.HireDate, new { @type="date", @class="form-control", required="required" });

    @Html.Label("Experience Level");
    @Html.TextBoxFor(model => model.ExperienceLevel, new { @type="number", min="1", max="10", @class="form-control", required="required" });

    <input type="submit" class="btn btn-dark" value="Save" />
}

Factory/Views/Engineers/Index.cshtml
@{
  Layout = "_Layout";
}

@using Factory.Models;
@model List<Factory.Models.Engineer>;

<h2>Engineers</h2>

@if (@Model.Count == 0)
{
  <p>No engineers have been added.</p>
}
else 
{
  <ul>
    @foreach (Engineer engineer in @Model)
    {
      <li>@Html.ActionLink($"{engineer.Name}", "Details", new { id = engineer.EngineerId })</li>
    }
  </ul>
}

<button class="btn btn-dark">@Html.ActionLink("Add New Engineer", "Create")</button>

Factory/Views/Home/Index.cshtml
@{
  Layout = "_Layout";
}

@using Factory.Models;

<div class="splash">
  <h1>Dr. Snuess' Factory</h1>
  <div class="row">
    <div class="col col-sm-3">
      <ul><h2>Engineers</h2>
        @foreach (Engineer engineer in ViewBag.Engineers)
        {
          <li>@Html.ActionLink($"{engineer.Name}", "Details", "Engineers", new { id = engineer.EngineerId })</li>
        }
      </ul>
      <button class="btn btn-dark">@Html.ActionLink("Add Engineer", "Create", "Engineers")</button>
    </div>

    <div class="col col-sm-3">
      <ul><h2>Machines</h2>
        @foreach (Machine machine in ViewBag.Machines)
        {
          <li>@Html.ActionLink($"{machine.Model}", "Details", "Machines", new { id = machine.MachineId })</li>
        }
      </ul>
      <button class="btn btn-dark">@Html.ActionLink("Add Machine", "Create", "Machines")</button>
    </div>
  </div>
</div>

Factory/Views/Machines/AddEngineer.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<h2>Add Engineer</h2>

<h4>Select an engineer that is licensed to repair @Html.DisplayFor(model => model.Model).</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.MachineId)

  @Html.Label("Engineer")
  @Html.DropDownList("EngineerId")

  <input type="submit" class="btn btn-dark" value="Save" />
}

Factory/Views/Machines/Create.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine;

<h2>Add a Machine</h2>

@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Model);
  @Html.TextBoxFor(model => model.Model, new { @class="form-control", required="required" });

  @Html.LabelFor(model => model.Manufacturer);
  @Html.TextBoxFor(model => model.Manufacturer, new { @class="form-control", required="required" });

  @Html.Label("Years in Operation");
  @Html.TextBoxFor(model => model.YearsInOperation, new { @type="number", @class="form-control", required="required" });

  @Html.Label("Last Serviced");
  @Html.TextBoxFor(model => model.LastServiced, new { @type="date", @class="form-control", required="required" });

  @Html.Label("Routine Maintenance Interval");
  @Html.TextBoxFor(model => model.MaintenanceInterval, new { @class="form-control", required="required" });

  <input type="submit" class="btn btn-dark" value="Add Machine" />
}

Factory/Views/Machines/Delete.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<h2>Delete Machine: @Html.DisplayFor(model => model.Model)</h2>

<p>Are you sure you want to delete this machine?</p>

@using (Html.BeginForm())
{
    <input type="submit" value="Delete" />
}

Factory/Views/Machines/Details.cshtml
@{
  Layout ="_Layout";
}

@model Factory.Models.Machine

<div class="details">
  <h2>@Html.DisplayFor(model => model.Model)</h2>

  <ul>
    <li>@Html.Label("Manufacturer"): @Html.DisplayFor(model => model.Manufacturer)</li>
    <li>@Html.Label("Years in Operation"): @Html.DisplayFor(model => model.YearsInOperation)</li>
    <li>@Html.Label("Date of Last Service"): @Html.DisplayFor(model => model.LastServiced)</li>
    <li>@Html.Label("Routine Maintenance Interval"): @Html.DisplayFor(model => model.MaintenanceInterval)</li>
    <li>@Html.Label("Engineers licensed for this machine"): 
        <ul>
        @if (@Model.Engineers.Count == 0)
        {
          <li>There are no engineers licensed to repair this machine.</li>
        }
        else
        {
          @foreach(var join in Model.Engineers)
          {
            <li><h3>@Html.ActionLink($"{join.Engineer.Name}", "Details", "Engineers", new { id = join.Engineer.EngineerId })</h3></li>
            @using (Html.BeginForm("DeleteEngineer", "Machines"))
            {
              @Html.Hidden("joinId", @join.EngineerMachineId)
              <input type="submit" value="Delete"/>
            }
          }
        }
        </ul>
    </li>
  </ul>
</div>

<button class="btn btn-dark">@Html.ActionLink("Add an Engineer", "AddEngineer", new { id = Model.MachineId })</button>
<button class="btn btn-dark">@Html.ActionLink("Edit Machine", "Edit", new { id = @Model.MachineId })</button>
<button class="btn btn-dark">@Html.ActionLink("Delete Machine", "Delete", new { id = @Model.MachineId })</button>

Factory/Views/Machines/Edit.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<h2>Edit: @Html.DisplayFor(model => model.Model)</h2>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.MachineId)

    @Html.LabelFor(model => model.Model)
    @Html.TextBoxFor(model => model.Model,  new { @class="form-control", required="required" })

    @Html.LabelFor(model => model.Manufacturer);
    @Html.TextBoxFor(model => model.Manufacturer, new { @class="form-control", required="required" });

    @Html.Label("Years in Operation");
    @Html.TextBoxFor(model => model.YearsInOperation, new { @type="number", @class="form-control", required="required" });

    @Html.Label("Last Serviced");
    @Html.TextBoxFor(model => model.LastServiced, new { @type="date", @class="form-control", required="required" });

    @Html.Label("Routine Maintenance Interval");
    @Html.TextBoxFor(model => model.MaintenanceInterval, new { @class="form-control", required="required" });

    <input type="submit" class="btn btn-dark" value="Save" />
}

Factory/Views/Machines/Index.cshtml
@{
  Layout = "_Layout";
}

@using Factory.Models;
@model List<Factory.Models.Machine>;

<h2>Machines</h2>

@if (@Model.Count == 0)
{
  <p>No machines have been added.</p>
}
else 
{
  <ul>
    @foreach (Machine machine in @Model)
    {
      <li>@Html.ActionLink($"{machine.Model}", "Details", new { id = machine.MachineId })</li>
    }
  </ul>
}

<button class="btn btn-dark">@Html.ActionLink("Add New Machine", "Create")</button>

Factory/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Dr. Snuess' Factory</title>
    <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css'>
    <link rel="stylesheet" href="~/css/styles.css">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg bg-transparent">
      <a class="navbar-brand" href="/">Home</a>
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="/Engineers">Engineers</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/Machines">Machines</a>
        </li>
      </ul>
    </nav>
    <div class="container-fluid">
      @RenderBody()
    </div>
  </body>
</html>